#pragma once
#include "Khronos\spirv.h"
#include <string>

using namespace spv;

enum WordType {
  TSourceLanguage,
  TExecutionModel,
  TAddressingModel,
  TMemoryModel,
  TExecutionMode,
  TStorageClass,
  TDim,
  TSamplerAddressingMode,
  TSamplerFilterMode,
  TFPFastMathModeShift,
  TFPFastMathModeMask,
  TFPRoundingMode,
  TLinkageType,
  TAccessQualifier,
  TFunctionParameterAttribute,
  TDecoration,
  TBuiltIn,
  TSelectionControl,
  TSelectionControlShift,
  TSelectionControlMask,
  TLoopControl,
  TLoopControlShift,
  TLoopControlMask,
  TFunctionControl,
  TFunctionControlShift,
  TFunctionControlMask,
  TMemorySemantics,
  TMemorySemanticsShift,
  TMemorySemanticsMask,
  TMemoryAccess,
  TMemoryAccessShift,
  TMemoryAccessMask,
  TExecutionScope,
  TGroupOperation,
  TKernelEnqueueFlags,
  TKernelProfilingInfo,
  TKernelProfilingInfoShift,
  TKernelProfilingInfoMask,
  TOp,
  TId,
  TLiteralNumber,
  TLiteralString
};

static std::string SourceLanguageStrings[] {
  "Unknown",
  "ESSL",
  "GLSL",
  "OpenCL",
};

static std::string ExecutionModelStrings[] {
  "Vertex",
  "TessellationControl",
  "TessellationEvaluation",
  "Geometry",
  "Fragment",
  "GLCompute",
  "Kernel",
};

static std::string AddressingModelStrings[] {
  "Logical",
  "Physical32",
  "Physical64",
};

static std::string MemoryModelStrings[] {
  "Simple",
  "GLSL450",
  "OpenCL12",
  "OpenCL20",
  "OpenCL21",
};

static std::string ExecutionModeStrings[] {
  "Invocations",
  "SpacingEqual",
  "SpacingFractionalEven",
  "SpacingFractionalOdd",
  "VertexOrderCw",
  "VertexOrderCcw",
  "PixelCenterInteger",
  "OriginUpperLeft",
  "EarlyFragmentTests",
  "PointMode",
  "Xfb",
  "DepthReplacing",
  "DepthAny",
  "DepthGreater",
  "DepthLess",
  "DepthUnchanged",
  "LocalSize",
  "LocalSizeHint",
  "InputPoints",
  "InputLines",
  "InputLinesAdjacency",
  "InputTriangles",
  "InputTrianglesAdjacency",
  "InputQuads",
  "InputIsolines",
  "OutputVertices",
  "OutputPoints",
  "OutputLineStrip",
  "OutputTriangleStrip",
  "VecTypeHint",
  "ContractionOff",
};

static std::string StorageClassStrings[] {
  "UniformConstant",
  "Input",
  "Uniform",
  "Output",
  "WorkgroupLocal",
  "WorkgroupGlobal",
  "PrivateGlobal",
  "Function",
  "Generic",
  "Private",
  "AtomicCounter",
};

static std::string DimStrings[] {
  "1D",
  "2D",
  "3D",
  "Cube",
  "Rect",
  "Buffer",
};

static std::string SamplerAddressingModeStrings[] {
  "None",
  "ClampToEdge",
  "Clamp",
  "Repeat",
  "RepeatMirrored",
};

static std::string SamplerFilterModeStrings[] {
  "Nearest",
  "Linear",
};

static std::string FPFastMathModeShiftStrings[] {
  "NotNaNShift",
  "NotInfShift",
  "NSZShift",
  "AllowRecipShift",
  "FastShift",
};

static std::string FPFastMathModeMaskStrings[] {
  "MaskNone",
  "NotNaNMask",
  "NotInfMask",
  "NSZMask",
  "AllowRecipMask",
  "FastMask",
};

static std::string FPRoundingModeStrings[] {
  "RTE",
  "RTZ",
  "RTP",
  "RTN",
};

static std::string LinkageTypeStrings[] {
  "Export",
  "Import",
};

static std::string AccessQualifierStrings[] {
  "ReadOnly",
  "WriteOnly",
  "ReadWrite",
};

static std::string FunctionParameterAttributeStrings[] {
  "Zext",
  "Sext",
  "ByVal",
  "Sret",
  "NoAlias",
  "NoCapture",
  "SVM",
  "NoWrite",
  "NoReadWrite",
};

static std::string DecorationStrings[] {
  "PrecisionLow",
  "PrecisionMedium",
  "PrecisionHigh",
  "Block",
  "BufferBlock",
  "RowMajor",
  "ColMajor",
  "GLSLShared",
  "GLSLStd140",
  "GLSLStd430",
  "GLSLPacked",
  "Smooth",
  "Noperspective",
  "Flat",
  "Patch",
  "Centroid",
  "Sample",
  "Invariant",
  "Restrict",
  "Aliased",
  "Volatile",
  "Constant",
  "Coherent",
  "Nonwritable",
  "Nonreadable",
  "Uniform",
  "NoStaticUse",
  "CPacked",
  "SaturatedConversion",
  "Stream",
  "Location",
  "Component",
  "Index",
  "Binding",
  "DescriptorSet",
  "Offset",
  "Alignment",
  "XfbBuffer",
  "Stride",
  "BuiltIn",
  "FuncParamAttr",
  "FPRoundingMode",
  "FPFastMathMode",
  "LinkageAttributes",
  "SpecId",
};

static std::string BuiltInStrings[] {
  "Position",
  "PointSize",
  "ClipVertex",
  "ClipDistance",
  "CullDistance",
  "VertexId",
  "InstanceId",
  "PrimitiveId",
  "InvocationId",
  "Layer",
  "ViewportIndex",
  "TessLevelOuter",
  "TessLevelInner",
  "TessCoord",
  "PatchVertices",
  "FragCoord",
  "PointCoord",
  "FrontFacing",
  "SampleId",
  "SamplePosition",
  "SampleMask",
  "FragColor",
  "FragDepth",
  "HelperInvocation",
  "NumWorkgroups",
  "WorkgroupSize",
  "WorkgroupId",
  "LocalInvocationId",
  "GlobalInvocationId",
  "LocalInvocationIndex",
  "WorkDim",
  "GlobalSize",
  "EnqueuedWorkgroupSize",
  "GlobalOffset",
  "GlobalLinearId",
  "WorkgroupLinearId",
  "SubgroupSize",
  "SubgroupMaxSize",
  "NumSubgroups",
  "NumEnqueuedSubgroups",
  "SubgroupId",
  "SubgroupLocalInvocationId",
};

static std::string SelectionControlStrings[]{
  "Flatten",
  "DontFlatten",
};

static std::string SelectionControlShiftStrings[] {
  "FlattenShift",
  "DontFlattenShift",
};

static std::string SelectionControlMaskStrings[] {
  "MaskNone",
  "FlattenMask",
  "DontFlattenMask",
};

static std::string LoopControlStrings[]{
  "Unroll",
  "DontUnroll",
};

static std::string LoopControlShiftStrings[] {
  "UnrollShift",
  "DontUnrollShift",
};

static std::string LoopControlMaskStrings[] {
  "MaskNone",
  "UnrollMask",
  "DontUnrollMask",
};

static std::string FunctionControlStrings[]{
  "Inline",
  "DontInline",
  "Pure",
  "Const",
};

static std::string FunctionControlShiftStrings[] {
  "InlineShift",
  "DontInlineShift",
  "PureShift",
  "ConstShift",
};

static std::string FunctionControlMaskStrings[] {
  "MaskNone",
  "InlineMask",
  "DontInlineMask",
  "PureMask",
  "ConstMask",
};

static std::string MemorySemanticsStrings[]{
  "Relaxed",
  "SequentiallyConsistent",
  "Acquire",
  "Release",
  "UniformMemory",
  "SubgroupMemory",
  "WorkgroupLocalMemory",
  "WorkgroupGlobalMemory",
  "AtomicCounterMemory",
  "ImageMemory",
};

static std::string MemorySemanticsShiftStrings[] {
  "RelaxedShift",
  "SequentiallyConsistentShift",
  "AcquireShift",
  "ReleaseShift",
  "UniformMemoryShift",
  "SubgroupMemoryShift",
  "WorkgroupLocalMemoryShift",
  "WorkgroupGlobalMemoryShift",
  "AtomicCounterMemoryShift",
  "ImageMemoryShift",
};

static std::string MemorySemanticsMaskStrings[] {
  "MaskNone",
  "RelaxedMask",
  "SequentiallyConsistentMask",
  "AcquireMask",
  "ReleaseMask",
  "UniformMemoryMask",
  "SubgroupMemoryMask",
  "WorkgroupLocalMemoryMask",
  "WorkgroupGlobalMemoryMask",
  "AtomicCounterMemoryMask",
  "ImageMemoryMask",
};

static std::string MemoryAccessStrings[]{
  "Volatile",
  "Aligned",
};

static std::string MemoryAccessShiftStrings[] {
  "VolatileShift",
  "AlignedShift",
};

static std::string MemoryAccessMaskStrings[] {
  "MaskNone",
  "VolatileMask",
  "AlignedMask",
};

static std::string ExecutionScopeStrings[] {
  "CrossDevice",
  "Device",
  "Workgroup",
  "Subgroup",
};

static std::string GroupOperationStrings[] {
  "Reduce",
  "InclusiveScan",
  "ExclusiveScan",
};

static std::string KernelEnqueueFlagsStrings[] {
  "NoWait",
  "WaitKernel",
  "WaitWorkGroup",
};

static std::string KernelProfilingInfoStrings[]{
  "CmdExecTime",
};

static std::string KernelProfilingInfoShiftStrings[] {
  "CmdExecTimeShift",
};

static std::string KernelProfilingInfoMaskStrings[] {
  "MaskNone",
  "CmdExecTimeMask",
};

static std::string OpStrings[] = {
  "Nop",
  "Source",
  "SourceExtension",
  "Extension",
  "ExtInstImport",
  "MemoryModel",
  "EntryPoint",
  "ExecutionMode",
  "TypeVoid",
  "TypeBool",
  "TypeInt",
  "TypeFloat",
  "TypeVector",
  "TypeMatrix",
  "TypeSampler",
  "TypeFilter",
  "TypeArray",
  "TypeRuntimeArray",
  "TypeStruct",
  "TypeOpaque",
  "TypePointer",
  "TypeFunction",
  "TypeEvent",
  "TypeDeviceEvent",
  "TypeReserveId",
  "TypeQueue",
  "TypePipe",
  "ConstantTrue",
  "ConstantFalse",
  "Constant",
  "ConstantComposite",
  "ConstantSampler",
  "ConstantNullPointer",
  "ConstantNullObject",
  "SpecConstantTrue",
  "SpecConstantFalse",
  "SpecConstant",
  "SpecConstantComposite",
  "Variable",
  "VariableArray",
  "Function",
  "FunctionParameter",
  "FunctionEnd",
  "FunctionCall",
  "ExtInst",
  "Undef",
  "Load",
  "Store",
  "Phi",
  "DecorationGroup",
  "Decorate",
  "MemberDecorate",
  "GroupDecorate",
  "GroupMemberDecorate",
  "Name",
  "MemberName",
  "String",
  "Line",
  "VectorExtractDynamic",
  "VectorInsertDynamic",
  "VectorShuffle",
  "CompositeConstruct",
  "CompositeExtract",
  "CompositeInsert",
  "CopyObject",
  "CopyMemory",
  "CopyMemorySized",
  "Sampler",
  "TextureSample",
  "TextureSampleDref",
  "TextureSampleLod",
  "TextureSampleProj",
  "TextureSampleGrad",
  "TextureSampleOffset",
  "TextureSampleProjLod",
  "TextureSampleProjGrad",
  "TextureSampleLodOffset",
  "TextureSampleProjOffset",
  "TextureSampleGradOffset",
  "TextureSampleProjLodOffset",
  "TextureSampleProjGradOffset",
  "TextureFetchTexelLod",
  "TextureFetchTexelOffset",
  "TextureFetchSample",
  "TextureFetchTexel",
  "TextureGather",
  "TextureGatherOffset",
  "TextureGatherOffsets",
  "TextureQuerySizeLod",
  "TextureQuerySize",
  "TextureQueryLod",
  "TextureQueryLevels",
  "TextureQuerySamples",
  "AccessChain",
  "InBoundsAccessChain",
  "SNegate",
  "FNegate",
  "Not",
  "Any",
  "All",
  "ConvertFToU",
  "ConvertFToS",
  "ConvertSToF",
  "ConvertUToF",
  "UConvert",
  "SConvert",
  "FConvert",
  "ConvertPtrToU",
  "ConvertUToPtr",
  "PtrCastToGeneric",
  "GenericCastToPtr",
  "Bitcast",
  "Transpose",
  "IsNan",
  "IsInf",
  "IsFinite",
  "IsNormal",
  "SignBitSet",
  "LessOrGreater",
  "Ordered",
  "Unordered",
  "ArrayLength",
  "IAdd",
  "FAdd",
  "ISub",
  "FSub",
  "IMul",
  "FMul",
  "UDiv",
  "SDiv",
  "FDiv",
  "UMod",
  "SRem",
  "SMod",
  "FRem",
  "FMod",
  "VectorTimesScalar",
  "MatrixTimesScalar",
  "VectorTimesMatrix",
  "MatrixTimesVector",
  "MatrixTimesMatrix",
  "OuterProduct",
  "Dot",
  "ShiftRightLogical",
  "ShiftRightArithmetic",
  "ShiftLeftLogical",
  "LogicalOr",
  "LogicalXor",
  "LogicalAnd",
  "BitwiseOr",
  "BitwiseXor",
  "BitwiseAnd",
  "Select",
  "IEqual",
  "FOrdEqual",
  "FUnordEqual",
  "INotEqual",
  "FOrdNotEqual",
  "FUnordNotEqual",
  "ULessThan",
  "SLessThan",
  "FOrdLessThan",
  "FUnordLessThan",
  "UGreaterThan",
  "SGreaterThan",
  "FOrdGreaterThan",
  "FUnordGreaterThan",
  "ULessThanEqual",
  "SLessThanEqual",
  "FOrdLessThanEqual",
  "FUnordLessThanEqual",
  "UGreaterThanEqual",
  "SGreaterThanEqual",
  "FOrdGreaterThanEqual",
  "FUnordGreaterThanEqual",
  "DPdx",
  "DPdy",
  "Fwidth",
  "DPdxFine",
  "DPdyFine",
  "FwidthFine",
  "DPdxCoarse",
  "DPdyCoarse",
  "FwidthCoarse",
  "EmitVertex",
  "EndPrimitive",
  "EmitStreamVertex",
  "EndStreamPrimitive",
  "ControlBarrier",
  "MemoryBarrier",
  "ImagePointer",
  "AtomicInit",
  "AtomicLoad",
  "AtomicStore",
  "AtomicExchange",
  "AtomicCompareExchange",
  "AtomicCompareExchangeWeak",
  "AtomicIIncrement",
  "AtomicIDecrement",
  "AtomicIAdd",
  "AtomicISub",
  "AtomicUMin",
  "AtomicUMax",
  "AtomicAnd",
  "AtomicOr",
  "AtomicXor",
  "LoopMerge",
  "SelectionMerge",
  "Label",
  "Branch",
  "BranchConditional",
  "Switch",
  "Kill",
  "Return",
  "ReturnValue",
  "Unreachable",
  "LifetimeStart",
  "LifetimeStop",
  "CompileFlag",
  "AsyncGroupCopy",
  "WaitGroupEvents",
  "GroupAll",
  "GroupAny",
  "GroupBroadcast",
  "GroupIAdd",
  "GroupFAdd",
  "GroupFMin",
  "GroupUMin",
  "GroupSMin",
  "GroupFMax",
  "GroupUMax",
  "GroupSMax",
  "GenericCastToPtrExplicit",
  "GenericPtrMemSemantics",
  "ReadPipe",
  "WritePipe",
  "ReservedReadPipe",
  "ReservedWritePipe",
  "ReserveReadPipePackets",
  "ReserveWritePipePackets",
  "CommitReadPipe",
  "CommitWritePipe",
  "IsValidReserveId",
  "GetNumPipePackets",
  "GetMaxPipePackets",
  "GroupReserveReadPipePackets",
  "GroupReserveWritePipePackets",
  "GroupCommitReadPipe",
  "GroupCommitWritePipe",
  "EnqueueMarker",
  "EnqueueKernel",
  "GetKernelNDrangeSubGroupCount",
  "GetKernelNDrangeMaxSubGroupSize",
  "GetKernelWorkGroupSize",
  "GetKernelPreferredWorkGroupSizeMultiple",
  "RetainEvent",
  "ReleaseEvent",
  "CreateUserEvent",
  "IsValidEvent",
  "SetUserEventStatus",
  "CaptureEventProfilingInfo",
  "GetDefaultQueue",
  "BuildNDRange",
  "SatConvertSToU",
  "SatConvertUToS",
  "AtomicIMin",
  "AtomicIMax",
};

static void* LUTPointers[]{
  &SourceLanguageStrings,
  &ExecutionModelStrings,
  &AddressingModelStrings,
  &MemoryModelStrings,
  &ExecutionModeStrings,
  &StorageClassStrings,
  &DimStrings,
  &SamplerAddressingModeStrings,
  &SamplerFilterModeStrings,
  &FPFastMathModeShiftStrings,
  &FPFastMathModeMaskStrings,
  &FPRoundingModeStrings,
  &LinkageTypeStrings,
  &AccessQualifierStrings,
  &FunctionParameterAttributeStrings,
  &DecorationStrings,
  &BuiltInStrings,
  &SelectionControlStrings,
  &SelectionControlShiftStrings,
  &SelectionControlMaskStrings,
  &LoopControlStrings,
  &LoopControlShiftStrings,
  &LoopControlMaskStrings,
  &FunctionControlStrings,
  &FunctionControlShiftStrings,
  &FunctionControlMaskStrings,
  &MemorySemanticsStrings,
  &MemorySemanticsShiftStrings,
  &MemorySemanticsMaskStrings,
  &MemoryAccessStrings,
  &MemoryAccessShiftStrings,
  &MemoryAccessMaskStrings,
  &ExecutionScopeStrings,
  &GroupOperationStrings,
  &KernelEnqueueFlagsStrings,
  &KernelProfilingInfoStrings,
  &KernelProfilingInfoShiftStrings,
  &KernelProfilingInfoMaskStrings,
  &OpStrings,
};

#include "lookups_gen.h"